/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package os_gui1;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.GraphicsConfiguration;
import java.awt.List;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


import  java.lang.*;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.util.Collections;
import java.util.Random;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author mahmoud ezat
 */
public class process_scheduling extends javax.swing.JFrame  {

    
    /**
     * Creates new form process_scheduling
     */
    Vector <ProcessPL> objVector = new Vector <ProcessPL>(50);
    int x=0;
    int SizeCount =0;
    boolean Addflag=true;
    String sAlgo;
    Random rand =new Random();
    
                 int counter=0;
   

    public void delete(int i){
        jPanel1.remove(objVector.get(i));
                       objVector.remove(i);
                        
    }
    public static int minmum(Vector<ProcessPL> x ){
        int min=Integer.parseInt(x.get(0).jTextFieldBlockingTime.getText());
        int ind=0;
       
       for(int i=0;i<x.size();i++){
           if(min>Integer.parseInt(x.get(i).jTextFieldBlockingTime.getText())){
               min=Integer.parseInt(x.get(i).jTextFieldBlockingTime.getText());
               ind=i;
           }
       }
       
       
       return ind; 
   }
    public void delay ()
    {
        int num = 200;  // get the delay factor from GUI
        try {
            Thread.sleep(150 * num); // 150 is here by try and error
        } 
        catch (InterruptedException ex) {  
            Logger.getLogger(process_scheduling.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    public process_scheduling() {
        initComponents();
        setDefaultCloseOperation(process_scheduling.DISPOSE_ON_CLOSE);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
		size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSpinnerBlockingTime = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSpinnerId = new javax.swing.JSpinner();
        jSpinnerPriority = new javax.swing.JSpinner();
        jSpinnerCpuTime = new javax.swing.JSpinner();
        jSpinnerCpuTimeSlice = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 70, 90, 23);
        getContentPane().add(jSpinnerBlockingTime);
        jSpinnerBlockingTime.setBounds(310, 170, 50, 30);

        jButton3.setText("Set");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 80, 80, 23);

        jButton4.setText("Rest");
        getContentPane().add(jButton4);
        jButton4.setBounds(50, 170, 90, 23);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 230, 590, 200);
        getContentPane().add(jSpinnerId);
        jSpinnerId.setBounds(310, 10, 50, 30);
        getContentPane().add(jSpinnerPriority);
        jSpinnerPriority.setBounds(310, 50, 50, 30);
        getContentPane().add(jSpinnerCpuTime);
        jSpinnerCpuTime.setBounds(310, 90, 50, 30);
        getContentPane().add(jSpinnerCpuTimeSlice);
        jSpinnerCpuTimeSlice.setBounds(310, 130, 50, 30);

        jLabel1.setText("Priority :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 60, 70, 14);

        jLabel2.setText("CpuTime :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 100, 80, 14);

        jLabel3.setText("CpuTimeSlice :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 140, 90, 14);

        jLabel4.setText("ArrivalTime");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 180, 90, 14);

        jLabel7.setText("ID :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 20, 20, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "FCFS", "Piriorty" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(50, 30, 90, 20);

        jButton5.setText("Simulate");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(50, 120, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(Addflag){
            ProcessPL ob = new ProcessPL();
            ob.setSize(150,150);
            ob.setVisible(true);
            ob.setLocation(x, 0);
            x+=180;
            objVector.add(ob);

            System.out.println(x);
            jPanel1.add(ob);

            jPanel1.repaint();
            repaint();
            setVisible(true);
            Addflag=false;
        }else{
            JOptionPane.showMessageDialog(rootPane, "You should set info for process before add another");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        int v1,v2,v3,v4,v5;
        v1 = (int)jSpinnerId.getValue();
        v2 = (int)jSpinnerPriority.getValue();
        v3 = (int)jSpinnerCpuTime.getValue();
        v4 = (int)jSpinnerCpuTimeSlice.getValue();
        v5 = (int)jSpinnerBlockingTime.getValue();

        if(objVector.size()!=0){
            if(v1>=0&&v2>0&&v3>0&&v4>0&&v5>=0){
            objVector.lastElement().jTextFieldId.setText(jSpinnerId.getValue().toString());
            objVector.lastElement().jTextFieldPriority.setText(jSpinnerPriority.getValue().toString());
            objVector.lastElement().jTextFieldCpuTime.setText(jSpinnerCpuTime.getValue().toString());
            objVector.lastElement().jTextFieldCpuTimeSlice.setText(jSpinnerCpuTimeSlice.getValue().toString());
            objVector.lastElement().jTextFieldBlockingTime.setText(jSpinnerBlockingTime.getValue().toString());
            objVector.lastElement().jTextField1.setText(jSpinnerCpuTime.getValue().toString());
            Addflag=true;
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "you should add process first ");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
               cusstomthread cThread = new cusstomthread(this,jPanel1,objVector,jComboBox1);
                   cThread.start();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(process_scheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(process_scheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(process_scheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(process_scheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new process_scheduling().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerBlockingTime;
    private javax.swing.JSpinner jSpinnerCpuTime;
    private javax.swing.JSpinner jSpinnerCpuTimeSlice;
    private javax.swing.JSpinner jSpinnerId;
    private javax.swing.JSpinner jSpinnerPriority;
    // End of variables declaration//GEN-END:variables
}
