/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package os_gui1;

import com.sun.glass.events.KeyEvent;
import java.awt.Component;
import java.awt.FontFormatException;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohamed Emad
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public test() throws FontFormatException, IOException {
        this.setUndecorated(true);
      //  this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordLabel = new javax.swing.JLabel();
        signIn = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        userIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        passwordLabel.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(240, 240, 240));
        passwordLabel.setText("Password :");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(430, 310, 180, 40);

        signIn.setFont(new java.awt.Font("Oswald", 0, 30)); // NOI18N
        signIn.setForeground(new java.awt.Color(0, 51, 102));
        signIn.setText("Sign In");
        signIn.setAutoscrolls(true);
        signIn.setBorder(null);
        signIn.setBorderPainted(false);
        signIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signIn.setFocusPainted(false);
        signIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signIn.setOpaque(false);
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });
        getContentPane().add(signIn);
        signIn.setBounds(660, 370, 120, 50);

        passwordField.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        passwordField.setForeground(new java.awt.Color(0, 51, 102));
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        passwordField.setCaretColor(new java.awt.Color(102, 0, 102));
        passwordField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(passwordField);
        passwordField.setBounds(610, 310, 220, 40);

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/User Account_96px.png"))); // NOI18N
        userIcon.setLabelFor(passwordField);
        getContentPane().add(userIcon);
        userIcon.setBounds(660, 224, 100, 70);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 450, 300, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Main_Background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1380, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        char[] input = passwordField.getPassword();
        if(isPasswordCorrect(input)){
            System.out.print("ok");
            
            System.out.print("ok2");
            new Home();
            System.out.print("ok3");
            }
        else {
            Component controllingFrame = null;
            //passwordField.setText("");
           // jLabel1.setText("Wrong Password!");
            JOptionPane.showMessageDialog(controllingFrame,"Invalid password. Try again.","Error Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_signInActionPerformed

    private  boolean isPasswordCorrect(char[] input) {
        boolean isCorrect = true;
        char[] correctPassword = {'0','0','0','0'};
        if (input.length != correctPassword.length) {
            isCorrect = false;
            
        } 
        else {
            isCorrect = Arrays.equals (input, correctPassword);
        }
        //Zero out the password.
        Arrays.fill(correctPassword,'0');
        return isCorrect;
    }
    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            char[] input = passwordField.getPassword();
            if(isPasswordCorrect(input)){
                System.out.print("ok");
                
                System.out.print("ok2");
                new Home();
                dispose();
                System.out.print("ok3");
                }
            else {
                Component controllingFrame = null;
                 //  jLabel1.setText("Wrong Password!");
JOptionPane.showMessageDialog(controllingFrame,"Invalid password. Try again.","Error Message",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new test().setVisible(true);
                } catch (FontFormatException ex) {
                    Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signIn;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
